@echo off
setlocal enabledelayedexpansion

REM ============================================================================
REM ARMA REFORGER RCON TOOL (ARRT) - MULTI-PLATFORM PORTABLE PACKER
REM ============================================================================

if "%~1"=="" (
    echo.
    echo [ERROR] Missing version argument.
    echo Usage:   pack-all.bat ^<SemVer^> [Configuration]
    echo Example: pack-all.bat 0.9.0-alpha.1
    echo          pack-all.bat 0.9.0-alpha.1 Release
    echo.
    exit /b 1
)

REM ----------------------------------------------------------------------------
REM 1. Version Normalization (strip 'v' prefix if provided: v0.9.0 -> 0.9.0)
REM ----------------------------------------------------------------------------
set "RAW_VER=%~1"
if /i "!RAW_VER:~0,1!"=="v" set "RAW_VER=!RAW_VER:~1!"
set "VERSION=!RAW_VER!"

REM Build configuration (defaults to Release; pass Debug as 2nd arg if needed)
set "BUILD_CONFIG=Release"
if not "%~2"=="" set "BUILD_CONFIG=%~2"

set "PACK_ID=ReforgerRcon"
set "PACK_TITLE=ARMA Reforger RCON Tool"
set "MAIN_EXE=ReforgerRcon.exe"
set "PROJECT_PATH=%~dp0ReforgerRcon\ReforgerRcon.csproj"
set "ICON_PATH=%~dp0ReforgerRcon\Assets\app.ico"
set "PUBLISH_WIN=%~dp0publish\win-x64"
set "PUBLISH_LINUX=%~dp0publish\linux-x64"
set "RELEASES_DIR=%~dp0releases"

REM Target output zip names requested:
set "ZIP_WIN=ARRT_v!VERSION!_win-x64.zip"
set "ZIP_LINUX=ARRT_v!VERSION!_linux-x64.zip"

echo ============================================================================
echo  PACKAGING MULTI-PLATFORM PORTABLE: %PACK_TITLE% v!VERSION!
echo  Configuration : !BUILD_CONFIG!
echo  Output Files  : 
echo    - !ZIP_WIN!
echo    - !ZIP_LINUX!
echo    - releases.win.json
echo    - %PACK_ID%-!VERSION!-full.nupkg
echo  (NO Setup.exe will be retained)
echo ============================================================================

REM Clean temporary publish directories
if exist "%~dp0publish" rmdir /s /q "%~dp0publish"

REM Ensure releases directory exists (do NOT delete so deltas can be computed)
if not exist "%RELEASES_DIR%" mkdir "%RELEASES_DIR%"

REM ----------------------------------------------------------------------------
REM [1/4] Publish Windows x64 (Self-Contained)
REM ----------------------------------------------------------------------------
echo.
echo [1/4] Compiling and publishing Windows x64 (!BUILD_CONFIG!, Self-Contained)...
dotnet publish "%PROJECT_PATH%" ^
    -c !BUILD_CONFIG! ^
    -r win-x64 ^
    --self-contained true ^
    /p:PublishSingleFile=false ^
    -o "%PUBLISH_WIN%"

if errorlevel 1 (
    echo [ERROR] dotnet publish for Windows failed.
    exit /b 1
)

REM ----------------------------------------------------------------------------
REM [2/4] Velopack Packaging for Windows
REM ----------------------------------------------------------------------------
echo.
echo [2/4] Running Velopack packaging for Windows...
vpk pack ^
    -u "%PACK_ID%" ^
    -v "%VERSION%" ^
    -p "%PUBLISH_WIN%" ^
    -e "%MAIN_EXE%" ^
    --packTitle "%PACK_TITLE%" ^
    --icon "%ICON_PATH%" ^
    -o "%RELEASES_DIR%"

if errorlevel 1 (
    echo [ERROR] Velopack packaging failed.
    exit /b 1
)

REM A. Delete any Setup.exe generated by Velopack (e.g. ReforgerRcon-win-Setup.exe)
if exist "%RELEASES_DIR%\*Setup.exe" del /f /q "%RELEASES_DIR%\*Setup.exe" >nul 2>&1
if exist "%RELEASES_DIR%\*setup.exe" del /f /q "%RELEASES_DIR%\*setup.exe" >nul 2>&1

REM B. Rename Velopack portable zip to ARRT_v<VERSION>_win-x64.zip
if exist "%RELEASES_DIR%\!ZIP_WIN!" del /f /q "%RELEASES_DIR%\!ZIP_WIN!" >nul 2>&1

if exist "%RELEASES_DIR%\%PACK_ID%-win-Portable.zip" (
    move /y "%RELEASES_DIR%\%PACK_ID%-win-Portable.zip" "%RELEASES_DIR%\!ZIP_WIN!" >nul
) else if exist "%RELEASES_DIR%\%PACK_ID%-Portable.zip" (
    move /y "%RELEASES_DIR%\%PACK_ID%-Portable.zip" "%RELEASES_DIR%\!ZIP_WIN!" >nul
)

REM ----------------------------------------------------------------------------
REM [3/4] Publish Linux x64 (Self-Contained)
REM ----------------------------------------------------------------------------
echo.
echo [3/4] Compiling and publishing Linux x64 (!BUILD_CONFIG!, Self-Contained)...
dotnet publish "%PROJECT_PATH%" ^
    -c !BUILD_CONFIG! ^
    -r linux-x64 ^
    --self-contained true ^
    /p:PublishSingleFile=false ^
    -o "%PUBLISH_LINUX%"

if errorlevel 1 (
    echo [ERROR] dotnet publish for Linux failed.
    exit /b 1
)

REM ----------------------------------------------------------------------------
REM [4/4] Create Linux x64 Portable ZIP: ARRT_v<VERSION>_linux-x64.zip
REM ----------------------------------------------------------------------------
echo.
echo [4/4] Creating Linux x64 Portable ZIP (!ZIP_LINUX!)...
if exist "%RELEASES_DIR%\!ZIP_LINUX!" del /f /q "%RELEASES_DIR%\!ZIP_LINUX!" >nul 2>&1
powershell -NoProfile -Command "Compress-Archive -Path '%PUBLISH_LINUX%\*' -DestinationPath '%RELEASES_DIR%\!ZIP_LINUX!' -Force"

if errorlevel 1 (
    echo [ERROR] Creating Linux zip failed.
    exit /b 1
)

REM ----------------------------------------------------------------------------
REM Summary
REM ----------------------------------------------------------------------------
echo.
echo ============================================================================
echo  PACKAGING COMPLETE!
echo  Files ready in releases\ folder:
echo    - !ZIP_WIN!
echo    - !ZIP_LINUX!
echo    - releases.win.json
echo    - %PACK_ID%-!VERSION!-full.nupkg
if exist "%RELEASES_DIR%\%PACK_ID%-!VERSION!-delta.nupkg" (
    echo    - %PACK_ID%-!VERSION!-delta.nupkg
)
echo ============================================================================

explorer "%RELEASES_DIR%"