@echo off
setlocal enabledelayedexpansion

REM ============================================================================
REM ARMA REFORGER RCON TOOL (ARRT) - MULTI-PLATFORM PORTABLE PACKER
REM ============================================================================

if "%~1"=="" (
    echo.
    echo [ERROR] Missing version argument.
    echo Usage:   pack-all.bat ^<SemVer^> [Configuration]
    echo Example: pack-all.bat 0.9.0-alpha.3
    echo          pack-all.bat 0.9.0-alpha.3 Debug
    echo.
    exit /b 1
)

REM ----------------------------------------------------------------------------
REM 1. Version Normalization (strip 'v' prefix if provided: v0.9.0 -> 0.9.0)
REM ----------------------------------------------------------------------------
set "RAW_VER=%~1"
if /i "!RAW_VER:~0,1!"=="v" set "RAW_VER=!RAW_VER:~1!"
set "VERSION=!RAW_VER!"

REM Build configuration (defaults to Debug)
set "BUILD_CONFIG=Debug"
if not "%~2"=="" set "BUILD_CONFIG=%~2"

set "PACK_ID=ReforgerRcon"
set "PACK_TITLE=ARMA Reforger RCON Tool"
set "MAIN_EXE=ReforgerRcon.exe"
set "PROJECT_PATH=%~dp0ReforgerRcon\ReforgerRcon.csproj"
set "PROJECT_DIR=%~dp0ReforgerRcon"
set "ICON_PATH=%PROJECT_DIR%\Assets\app.ico"
set "PUBLISH_WIN=%~dp0publish\win-x64"
set "PUBLISH_LINUX=%~dp0publish\linux-x64"
set "RELEASES_DIR=%~dp0releases"
set "STAGE_SCRIPT=%~dp0stage-portable.ps1"

set "ZIP_WIN=ARRT_v!VERSION!_win-x64.zip"
set "ZIP_LINUX=ARRT_v!VERSION!_linux-x64.zip"

echo ============================================================================
echo  PACKAGING MULTI-PLATFORM PORTABLE: %PACK_TITLE% v!VERSION!
echo  Configuration : !BUILD_CONFIG!
echo  Features      : Single-File, ReadyToRun (R2R AOT), Self-Contained, PDBs, GeoIP
echo  Platforms     : win-x64, linux-x64
echo  Output Files  : 
echo    - !ZIP_WIN! (Includes .pdbs, GeoIP, and staged base .nupkg for deltas)
echo    - !ZIP_LINUX! (Includes .pdbs and GeoIP)
echo    - releases.win.json
echo    - %PACK_ID%-!VERSION!-full.nupkg
echo ============================================================================

REM Clean temporary publish and Velopack directories
if exist "%TEMP%\velopack" rmdir /s /q "%TEMP%\velopack" >nul 2>&1
if exist "%~dp0publish" rmdir /s /q "%~dp0publish"

REM Ensure releases directory exists (retained so Velopack can compute deltas)
if not exist "%RELEASES_DIR%" mkdir "%RELEASES_DIR%"

REM ----------------------------------------------------------------------------
REM [1/4] Publish Windows x64 (Debug, Self-Contained, Single-File, ReadyToRun)
REM ----------------------------------------------------------------------------
echo.
echo [1/4] Compiling and publishing Windows x64 (%BUILD_CONFIG%, Single-File, ReadyToRun)...
dotnet publish "%PROJECT_PATH%" ^
    -c %BUILD_CONFIG% ^
    -r win-x64 ^
    --self-contained true ^
    /p:PublishSingleFile=true ^
    /p:PublishReadyToRun=true ^
    /p:DebugType=portable ^
    /p:DebugSymbols=true ^
    /p:IncludeNativeLibrariesForSelfExtract=true ^
    -o "%PUBLISH_WIN%"

if errorlevel 1 (
    echo [ERROR] dotnet publish for Windows failed.
    exit /b 1
)

REM Fallback verification: ensure GeoIP mmdb files exist in the publish directory
if not exist "%PUBLISH_WIN%\GeoIP" mkdir "%PUBLISH_WIN%\GeoIP"
if exist "%PROJECT_DIR%\GeoIP\*.mmdb" copy /y "%PROJECT_DIR%\GeoIP\*.mmdb" "%PUBLISH_WIN%\GeoIP\" >nul 2>&1
if exist "%~dp0GeoIP\*.mmdb" copy /y "%~dp0GeoIP\*.mmdb" "%PUBLISH_WIN%\GeoIP\" >nul 2>&1
if exist "%PROJECT_DIR%\appdata\geoip\*.mmdb" copy /y "%PROJECT_DIR%\appdata\geoip\*.mmdb" "%PUBLISH_WIN%\GeoIP\" >nul 2>&1

REM ----------------------------------------------------------------------------
REM [2/4] Velopack Packaging for Windows
REM ----------------------------------------------------------------------------
echo.
echo [2/4] Running Velopack packaging for Windows (with PDBs and GeoIP included)...
vpk pack ^
    -u "%PACK_ID%" ^
    -v "%VERSION%" ^
    -p "%PUBLISH_WIN%" ^
    -e "%MAIN_EXE%" ^
    --packTitle "%PACK_TITLE%" ^
    --icon "%ICON_PATH%" ^
    --exclude "^$" ^
    -o "%RELEASES_DIR%"

if errorlevel 1 (
    echo [ERROR] Velopack packaging failed.
    exit /b 1
)

REM Delete any Setup.exe generated by Velopack
if exist "%RELEASES_DIR%\*Setup.exe" del /f /q "%RELEASES_DIR%\*Setup.exe" >nul 2>&1
if exist "%RELEASES_DIR%\*setup.exe" del /f /q "%RELEASES_DIR%\*setup.exe" >nul 2>&1

REM Rename Velopack portable zip to ARRT_v<VERSION>_win-x64.zip
if exist "%RELEASES_DIR%\!ZIP_WIN!" del /f /q "%RELEASES_DIR%\!ZIP_WIN!" >nul 2>&1

if exist "%RELEASES_DIR%\%PACK_ID%-win-Portable.zip" move /y "%RELEASES_DIR%\%PACK_ID%-win-Portable.zip" "%RELEASES_DIR%\!ZIP_WIN!" >nul
if exist "%RELEASES_DIR%\%PACK_ID%-Portable.zip" move /y "%RELEASES_DIR%\%PACK_ID%-Portable.zip" "%RELEASES_DIR%\!ZIP_WIN!" >nul

REM ----------------------------------------------------------------------------
REM [2.1/4] Staging base .nupkg for deltas, mirroring GeoIP & PDBs, fixing timestamps
REM ----------------------------------------------------------------------------
echo.
echo [2.1/4] Staging delta package and normalizing portable archive entries...
if exist "%STAGE_SCRIPT%" powershell -NoProfile -ExecutionPolicy Bypass -File "%STAGE_SCRIPT%" "%RELEASES_DIR%\!ZIP_WIN!" "%RELEASES_DIR%\%PACK_ID%-%VERSION%-full.nupkg" "%PUBLISH_WIN%"
if not exist "%STAGE_SCRIPT%" echo [WARNING] stage-portable.ps1 not found at "%STAGE_SCRIPT%". Skipping staging step.

REM ----------------------------------------------------------------------------
REM [3/4] Publish Linux x64 (Debug, Self-Contained, Single-File, ReadyToRun)
REM ----------------------------------------------------------------------------
echo.
echo [3/4] Compiling and publishing Linux x64 (%BUILD_CONFIG%, Single-File, ReadyToRun)...
dotnet publish "%PROJECT_PATH%" ^
    -c %BUILD_CONFIG% ^
    -r linux-x64 ^
    --self-contained true ^
    /p:PublishSingleFile=true ^
    /p:PublishReadyToRun=true ^
    /p:DebugType=portable ^
    /p:DebugSymbols=true ^
    /p:IncludeNativeLibrariesForSelfExtract=true ^
    -o "%PUBLISH_LINUX%"

if errorlevel 1 (
    echo [ERROR] dotnet publish for Linux failed.
    exit /b 1
)

REM Fallback verification: ensure GeoIP mmdb files exist in Linux publish directory
if not exist "%PUBLISH_LINUX%\GeoIP" mkdir "%PUBLISH_LINUX%\GeoIP"
if exist "%PROJECT_DIR%\GeoIP\*.mmdb" copy /y "%PROJECT_DIR%\GeoIP\*.mmdb" "%PUBLISH_LINUX%\GeoIP\" >nul 2>&1
if exist "%~dp0GeoIP\*.mmdb" copy /y "%~dp0GeoIP\*.mmdb" "%PUBLISH_LINUX%\GeoIP\" >nul 2>&1
if exist "%PROJECT_DIR%\appdata\geoip\*.mmdb" copy /y "%PROJECT_DIR%\appdata\geoip\*.mmdb" "%PUBLISH_LINUX%\GeoIP\" >nul 2>&1

REM ----------------------------------------------------------------------------
REM [4/4] Create Linux x64 Portable ZIP: ARRT_v<VERSION>_linux-x64.zip
REM ----------------------------------------------------------------------------
echo.
echo [4/4] Creating Linux x64 Portable ZIP (!ZIP_LINUX!)...
if exist "%RELEASES_DIR%\!ZIP_LINUX!" del /f /q "%RELEASES_DIR%\!ZIP_LINUX!" >nul 2>&1
powershell -NoProfile -Command "Compress-Archive -Path '%PUBLISH_LINUX%\*' -DestinationPath '%RELEASES_DIR%\!ZIP_LINUX!' -Force"

if errorlevel 1 (
    echo [ERROR] Creating Linux zip failed.
    exit /b 1
)

REM ----------------------------------------------------------------------------
REM Summary
REM ----------------------------------------------------------------------------
echo.
echo ============================================================================
echo  PACKAGING COMPLETE!
echo  Files ready in releases\ folder:
echo    - !ZIP_WIN! (Includes root .pdbs, root GeoIP, valid timestamps, delta-ready)
echo    - !ZIP_LINUX! (Includes .pdbs, GeoIP)
echo    - releases.win.json
echo    - %PACK_ID%-%VERSION%-full.nupkg
if exist "%RELEASES_DIR%\%PACK_ID%-%VERSION%-delta.nupkg" echo    - %PACK_ID%-%VERSION%-delta.nupkg
echo ============================================================================

explorer "%RELEASES_DIR%"